# Generated by Django 5.1.7 on 2025-04-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('DATA', 'Data'), ('VOICE', 'Thoại'), ('SMS', 'SMS'), ('COMBO', 'Combo')], max_length=5)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_days', models.IntegerField()),
                ('data_volume', models.IntegerField(blank=True, null=True)),
                ('voice_minutes', models.IntegerField(blank=True, null=True)),
                ('sms_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
