# Generated by Django 5.1.7 on 2025-04-19 18:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceplan',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='data_speed',
            field=models.CharField(blank=True, choices=[('3G', '3G'), ('4G', '4G'), ('5G', '5G')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='duration_days',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_plans', models.ManyToManyField(related_name='promotions', to='services.serviceplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('data_usage', models.FloatField(default=0.0)),
                ('remaining_data', models.FloatField(default=0.0)),
                ('call_minutes', models.IntegerField(default=0)),
                ('remaining_minutes', models.IntegerField(default=0)),
                ('sms_used', models.IntegerField(default=0)),
                ('remaining_sms', models.IntegerField(default=0)),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('service_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='services.serviceplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
